INSERT INTO menu_items (name, description, price, image_url) VALUES ('rice', 'Delicious bowl of basmati rice, cooked to perfection!',  200, 'https://www.recipetineats.com/wp-content/uploads/2020/03/Basmati-rice.jpg?resize=650,520');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('chicken', 'Our special grilled chicken with the added secret sauce!',  500, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/grilled-chicken-horizontal-1532030541.jpg?crop=1xw:1xh;center,top&resize=768:*');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('salad', 'Add some greens to your meal bacause #HEALTH',  300, 'https://www.culinaryhill.com/wp-content/uploads/2020/06/Easy-Garden-Salad-Recipe-Culinary-Hill-LR-06.jpg');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('rice 1', 'Delicious bowl of basmati rice, cooked to perfection!',  200, 'https://www.recipetineats.com/wp-content/uploads/2020/03/Basmati-rice.jpg?resize=650,520');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('chicken 1', 'Our special grilled chicken with the added secret sauce!',  500, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/grilled-chicken-horizontal-1532030541.jpg?crop=1xw:1xh;center,top&resize=768:*');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('salad 1', 'Add some greens to your meal bacause #HEALTH',  300, 'https://www.culinaryhill.com/wp-content/uploads/2020/06/Easy-Garden-Salad-Recipe-Culinary-Hill-LR-06.jpg');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('rice 2', 'Delicious bowl of basmati rice, cooked to perfection!',  200, 'https://www.recipetineats.com/wp-content/uploads/2020/03/Basmati-rice.jpg?resize=650,520');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('chicken 2', 'Our special grilled chicken with the added secret sauce!',  500, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/grilled-chicken-horizontal-1532030541.jpg?crop=1xw:1xh;center,top&resize=768:*');
INSERT INTO menu_items (name, description, price, image_url) VALUES ('salad 2', 'Add some greens to your meal bacause #HEALTH',  300, 'https://www.culinaryhill.com/wp-content/uploads/2020/06/Easy-Garden-Salad-Recipe-Culinary-Hill-LR-06.jpg');
